// Copyright 2021 Board of Trustees of the University of Illinois
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/rokwire/logging-library-go/errors"
	"github.com/rokwire/logging-library-go/logs"
	"github.com/rokwire/logging-library-go/logutils"
)

type handlerFunc = func(*logs.Log, http.ResponseWriter, *http.Request)

type WebAdapter struct {
	logger *logs.Logger
}

func (we WebAdapter) Start() {
	// Empty permissions indicates that no permissions are required
	http.HandleFunc("/test", we.wrapFunc(we.test))

	http.ListenAndServe(":5000", nil)
}

// test endpoint tests logsging
func (we WebAdapter) test(l *logs.Log, w http.ResponseWriter, req *http.Request) {
	param := req.URL.Query().Get("param")
	l.AddContext("param", param)

	err := checkParam(param)
	if err != nil {
		l.RequestErrorAction(w, logutils.ActionValidate, logutils.TypeQueryParam, nil, err, http.StatusBadRequest, false)
		return
	}

	l.Info("Success")

	l.RequestSuccess(w)
}

func checkParam(param string) error {
	if param == "test" {
		return nil
	}

	return errors.ErrorData(logutils.StatusInvalid, logutils.TypeArg, &logutils.FieldArgs{"param": param})
}

// wrapFunc provides a standard wrapper that performs request logsging
func (we WebAdapter) wrapFunc(handler handlerFunc) http.HandlerFunc {
	// Receive request with tokens generated by auth service
	return func(w http.ResponseWriter, req *http.Request) {
		logsObj := we.logger.NewRequestLog(req)

		logsObj.RequestReceived()
		handler(logsObj, w, req)
		logsObj.RequestComplete()
	}
}

// NewWebAdapter creates new WebAdapter instance
func NewWebAdapter(logger *logs.Logger) WebAdapter {
	return WebAdapter{logger: logger}
}

func main() {
	//Instantiate a logger for each service
	var logger = logs.NewLogger("example", nil)
	logger.SetLevel(logs.Debug)

	var random = 1234
	logger.Infof("Starting service: %d", random)
	logger.InfoWithFields("ENV_VAR", logutils.Fields{"name": "test", "val": 123})

	go CallTest()

	// Instantiate and start a new WebAdapter
	adapter := NewWebAdapter(logger)
	adapter.Start()
}

func CallTest() (*http.Response, error) {
	time.Sleep(2 * time.Second)

	req, err := http.NewRequest("GET", "http://127.0.0.1:5000/test", nil)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Authorization", "example_token")
	req.Header.Set("Header", "test")
	req.Header.Set("span-id", "4313")

	q := req.URL.Query()
	q.Add("param", "test2")
	req.URL.RawQuery = q.Encode()

	fmt.Println(req.URL.String())

	client := &http.Client{}
	return client.Do(req)
}
